routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (Auth::user()) {
		return redirect(route('home'));
	}
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('users', 'UsersController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::resource('segments', 'SegmentsController', ['except' => ['show']]);
	Route::resource('companies', 'CompaniesController', ['except' => ['show']]);
	Route::resource('customers', 'CustomersController', ['except' => ['show']]);
	Route::get('customers/approving-list', ['as' => 'customers.approving-list', 'uses' => 'CustomersController@approvingList']);
	Route::get('customers/{customer}/approve', ['as' => 'customers.approve', 'uses' => 'CustomersController@approve']);
	Route::get('customers/{customer}/repprove', ['as' => 'customers.repprove', 'uses' => 'CustomersController@repprove']);
});

app/Models/Segment.php
<?php

namespace App\Models;

use App\Models\Traits\HasImage;
use Illuminate\Database\Eloquent\Model;

class Segment extends Model
{
    use HasImage;

    protected $fillable = [
        'name',
        'cropinfo',
        'active',
    ];

    public function companies()
    {
        return $this->hasMany(Company::class);
    }

    public static function forApi()
    {
        $data = [];

        $segments = self::where('active', true)
            ->whereHas('companies', function ($query) {
                $query->where('active', true);
            })
            ->orderBy('name')
            ->get();

        foreach ($segments as $segment) {
            $data[] = [
                'id' => $segment->id,
                'name' => $segment->name,
            ];
        }

        return $data;
    }
}

app/Http/Controllers/Api/SegmentsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Segment;

class SegmentsController extends Controller {

    public function index()
    {
        return $this->sendResponse(Segment::forApi(), 'List of segments');
    }

}

app/Http/Controllers/SegmentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Segment;
use App\Http\Requests\SegmentRequest;
use Illuminate\Support\Facades\Hash;

class SegmentsController extends Controller
{
    public function index(Segment $model)
    {
        $this->authorize('index', Segment::class);

        return view('segments.index', ['segments' => $model->paginate(15)]);
    }

    public function create()
    {
        $this->authorize('create', Segment::class);

        return view('segments.create', ['segment' => new Segment(),]);
    }

    public function store(SegmentRequest $request, Segment $model)
    {
        $model->fill($request->all());
        $this->authorize('store', $model);
        $model->save();

        $request->file('file')->storeAs(
            'segments', $model->id, [
                'disk' => 'my_files',
            ]
        );

        return redirect(route('segments.index'))->withStatus(__('Segmento criado.'));
    }

    public function edit($id)
    {
        $model = Segment::findOrFail($id);
        $this->authorize('edit', $model);

        return view('segments.edit', ['segment' => $model,]);
    }

    public function update(SegmentRequest $request, $id)
    {
        $model = Segment::findOrFail($id);
        $model->fill($request->all());
        $this->authorize('update', $model);
        $model->save();

        if ($request->hasFile('file')) {
            $request->file('file')->storeAs(
                'public/segments', $model->id, [
                    'disk' => 'my_files',
                ]
            );
        }

        return redirect(route('segments.index'))->withStatus(__('Segmento alterado.'));
    }
}

resources/views/segments/create.blade.php
@extends('layouts.app', ['activePage' => 'segments', 'titlePage' => __('Novo segmento')])

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="{{ route('segments.store') }}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    {{-- @method('put') --}}
                    
                    <div class="card ">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">{{ __('Criar segmento') }}</h4>
                            <p class="card-category">{{ __('Informações do segmento') }}</p>
                        </div>
                        <div class="card-body ">
                            @if (session('status'))
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
                                            <i class="material-icons">close</i>
                                        </button>
                                        <span>{{ session('status') }}</span>
                                    </div>
                                </div>
                            </div>
                            @endif
                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                        <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nome') }}" value="{{ old('name', null) }}" required="true" aria-required="true"/>
                                        @if ($errors->has('name'))
                                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Imagem') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('file') ? ' has-danger' : '' }}">
                                        <input class="form-control" name="file" id="input-file" type="file" value="{{ old('file', null) }}" required="true" aria-required="true" style="position: relative; opacity: 1; z-index: 0;" placeholder="Selecione o arquivo" />
                                        <span id="" class="error text-info" for="input-file">Dimensões: 553 x 322 px</span>
                                        <br>
                                        @if ($errors->has('file'))
                                            <span id="file-error" class="error text-danger" for="input-file">{{ $errors->first('file') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-9">
                                    <div class="checkbox">
                                        <label>
                                            <input type="hidden" name="active" value="0">
                                            <input type="checkbox" name="active" value="1" {{ old('active', null) ? 'checked' : '' }}> Este segmento está ativo?
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-primary">{{ __('Salvar') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/segments/edit.blade.php
@extends('layouts.app', ['activePage' => 'segments', 'titlePage' => __('Editar segmento')])

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="{{ route('segments.update', $segment->id) }}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    
                    <div class="card ">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">{{ $segment->name }}</h4>
                            <p class="card-category">{{ __('Informações do segmento') }}</p>
                        </div>
                        <div class="card-body ">
                            @if (session('status'))
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
                                            <i class="material-icons">close</i>
                                        </button>
                                        <span>{{ session('status') }}</span>
                                    </div>
                                </div>
                            </div>
                            @endif
                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                        <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Nome') }}" value="{{ old('name', $segment->name) }}" required="true" aria-required="true"/>
                                        @if ($errors->has('name'))
                                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2 col-form-label">{{ __('Imagem') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('file') ? ' has-danger' : '' }}">
                                        <input class="form-control" name="file" id="input-file" type="file" value="{{ old('file', null) }}"  style="position: relative; opacity: 1; z-index: 0;" placeholder="Selecione o arquivo" />
                                        <span id="" class="error text-info" for="input-file">Dimensões: 553 x 322 px</span>
                                        <br>
                                        @if ($errors->has('file'))
                                            <span id="file-error" class="error text-danger" for="input-file">{{ $errors->first('file') }}</span>
                                        @endif
                                        @if(file_exists(storage_path('app/public/segments/' . $segment->id)))
                                            <img src="{{ url('storage/segments/' . $segment->id) }}" alt="">
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-9">
                                    <div class="checkbox">
                                        <label>
                                            <input type="hidden" name="active" value="0">
                                            <input type="checkbox" name="active" value="1" {{ old('active', $segment->active) ? 'checked' : '' }}> Este segmento está ativo?
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-primary">{{ __('Salvar') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/segments/index.blade.php
@extends('layouts.app', ['activePage' => 'segments', 'titlePage' => __('Gerenciar segmentos')])

@section('content')

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Segmentos</h4>
                        <p class="card-category"> Gerenciamento de segmentos aos quais pertencem as empresas dos teasers</p>
                    </div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
                                            <i class="material-icons">close</i>
                                        </button>
                                        <span>{{ session('status') }}</span>
                                    </div>
                                </div>
                            </div>
                        @endif
                        @can('create', App\Models\Segment::class)
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{ route('segments.create') }}" class="btn btn-sm btn-primary">Novo segmento</a>
                                </div>
                            </div>
                        @endcan
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                    <tr>
                                        <th>
                                            Nome
                                        </th>
                                        <th>
                                            Ativo
                                        </th>
                                        <th class="text-right">
                                            Ações
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($segments as $segment)
                                        <tr>
                                            <td>
                                                {{ $segment->name }}
                                            </td>
                                            <td>
                                                {{ $segment->active ? 'Sim' : 'Não' }}
                                            </td>
                                            <td class="td-actions text-right">
                                                <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('segments.edit', $segment->id) }}" data-original-title="editar" title="editar">
                                                    <i class="material-icons">edit</i>
                                                    <div class="ripple-container"></div>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-12 text-right">
                                {{ $segments->appends(request()->except(['page','_token']))->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    @endsection